### PR TITLE
Catch up with master and add regression test from cclib-data

### PR DESCRIPTION
**Pull request by langner**
If you rebase with cclib/master this should just have the regression test moved over from cclib/cclib-data#74

### CODE REVIEW

**Comment by berquist** [comment]
I think I understand what's going on here, but it is correct that this is a PR against `berquist/qchem` and not `berquist/master`? I'm making the PR from `master` (bad form, I know).

**Comment by langner** [comment]
> think I understand what's going on here, but it is correct that this is a PR against berquist/qchem and not berquist/master? I'm making the PR from master (bad form, I know).

**Comment by berquist** [comment]
Sorry, I was looking at the cclib-data PR. You were correct the first time.

**Comment by langner** [comment]
> Sorry, I was looking at the cclib-data PR. You were correct the first time.

OK, changed back :)

**Pull request merged**
